PWS-31: Update npm packages
wunderio/frontend-project pull request #73
Opened 2021-11-19 10:16 UTC by lauriskuznecovs

## Link to ticket:

https://wunder.atlassian.net/browse/PSW-31

## Changes proposed in this PR:
- change a
- change b

## How to test:
1. do this
1. then do that
1. you should now see xyz

## Link to feature environment:
<add silta url here>

2022-04-01 12:06 UTC, WunderNieves requested changes
All vulnerabilities are gone! 👍
But about the lint tool, there are errors in a wsl environment due to line endings. Adding "endOfLine": "auto" in the .prettierrc file solves this, so I'd suggest adding that line of code there and test in mac again to make sure that everything is still fine (from my experience, I had this issue before and after that addition everything was still fine in every environment)

2022-04-04 05:28 UTC, dcorb commented
I found this in Prettier https://github.com/prettier/prettier/issues/6932, the reason they change `endOfLine` from auto to "`lf`", it was to avoid some problems, and he says that LF is the standard in dev world.

_Because developers were contributing to repos from both *nix and Windows machines, end of lines ended up being different in neighbouring files and even jumped from one style to another in files between commits. In addition to a discomfort and unnecessary diffs coming out of this inconsistency, it was also a source of real bugs_

2022-04-04 10:26 UTC, WunderNieves commented
I have LF chosen in my VS Code and also in prettier settings, so it seemed that the problem was with git. Running this command "git config --global core.autocrlf false" as stated here https://stackoverflow.com/questions/25724969/sourcetree-line-ending-issue fixed the issue. So we can actually get rid of this line "endOfLine": "lf"

2022-04-04 10:30 UTC, WunderNieves approved these changes

2022-04-04 11:26 UTC, merged